#!/usr/bin/env bash
# SessionStart hook: auto-generate yesterday's work summary if not yet done.
# Runs skill-miner today --date <yesterday> and saves to memory/daily/.
# Silent on failure (never blocks session start).

set -uo pipefail

MEMORY_DIR="${HOME}/.claude/projects/C--Users-yuuji/memory/daily"
SKILL_MINER="${HOME}/skill-miner/target/debug/skill-miner.exe"
LOG_FILE="${HOME}/.claude/skill-miner-plugin/daily-summary.log"

# Ensure dirs exist
mkdir -p "${MEMORY_DIR}"
mkdir -p "$(dirname "${LOG_FILE}")"

# Calculate yesterday's date
YESTERDAY=$(date -d "yesterday" +%Y-%m-%d 2>/dev/null || date -v-1d +%Y-%m-%d 2>/dev/null)
if [ -z "${YESTERDAY}" ]; then
    echo "$(date -Iseconds) ERROR: cannot compute yesterday's date" >> "${LOG_FILE}"
    exit 0
fi

OUTPUT_FILE="${MEMORY_DIR}/${YESTERDAY}.md"

# Already done? Skip.
if [ -f "${OUTPUT_FILE}" ]; then
    exit 0
fi

# Binary exists?
if [ ! -x "${SKILL_MINER}" ]; then
    echo "$(date -Iseconds) ERROR: skill-miner binary not found" >> "${LOG_FILE}"
    exit 0
fi

echo "$(date -Iseconds) Generating summary for ${YESTERDAY}..." >> "${LOG_FILE}"

# Run skill-miner for yesterday, all carriers
# Run each carrier separately, concat results
SUMMARY=""
for carrier in claude gemini codex; do
    PART=$(timeout 60 "${SKILL_MINER}" today --date "${YESTERDAY}" --format summary --source "${carrier}" --no-dump 2>&1) || true
    # Filter noise lines (Saved:, Note:, empty session counts)
    PART=$(echo "${PART}" | grep -v '^Saved:' | grep -v '^Note:' | grep -v '0 sessions')
    # Skip if empty after filtering
    if [ -n "$(echo "${PART}" | tr -d '[:space:]')" ]; then
        SUMMARY="${SUMMARY}## ${carrier^}"$'\n'"${PART}"$'\n\n'
    fi
done

# If empty or only whitespace, skip creating the file
if [ -z "$(echo "${SUMMARY}" | tr -d '[:space:]')" ]; then
    echo "$(date -Iseconds) No activity found for ${YESTERDAY}" >> "${LOG_FILE}"
    exit 0
fi

# Write the summary with frontmatter
cat > "${OUTPUT_FILE}" << EOF
---
name: daily-${YESTERDAY}
description: ${YESTERDAY} の作業要約 (auto-generated by daily-summary hook)
type: project
---

# ${YESTERDAY} 作業要約

${SUMMARY}
EOF

echo "$(date -Iseconds) Saved: ${OUTPUT_FILE}" >> "${LOG_FILE}"

# Git push check
"${SKILL_MINER}" check --save 2>/dev/null || true

# Output hook result
cat <<HOOKEOF
{
  "hookSpecificOutput": {
    "hookEventName": "SessionStart",
    "additionalContext": "daily-summary: Generated ${YESTERDAY} summary → ${OUTPUT_FILE}"
  }
}
HOOKEOF

exit 0
